server:
 servlet:
  context-path: /travel



## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database

jpa:
 generate-ddl: true
 properties:
  hibernate:
   dialect: org.hibernate.dialect.MySQL5InnoDBDialect
   ddl-auto: create
   defer-datasource-initialization: 'true'

sql:
    init:
      mode: always
